server:
  port: 9012

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9011/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: springcloud-product-server

