server:
  port: 9014

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9011/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/freemasony/springcloud-parent
          search-paths: springcloud-config-center/config
          username: zhoujianth@163.com
          password: zhoujianth9895