server:
  port: 9014

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9011/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri:
